DOXYFILE = 'Doxyfile'

LINKS_NAVBAR1 = [
    ('Classes', 'annotated', []),
    ('Namespace', 'namespacezipios', []),
]

LINKS_NAVBAR2 = []

FINE_PRINT = 'zipwrapper++ documentation. Generated by Doxygen and m.css.'

THEME_COLOR = '#22272e'
FAVICON = ''
